### ISSUE TITLE
scaling issues.

### ISSUE THREAD

**Issue by Kerbal410** [BrettRyland/BDArmory-Extended#11]
the scaling options on the deployable missile rail (non-reloadable) doesn't work. also, the title of the new sonar and description of the Tigershark are broken (the #loc is visible). the sonar may need a little work with the RWR Threat Type UNKNOWN.

**Comment by Kerbal410** [comment]
I didn't see the sliders on the torpedo tube, but even at max width the tigerfish doesn't work. when fired, they just explode.

**Comment by Kerbal410** [comment]
Sorry, I meant even with the torpedo tubes at max width

**Comment by SuicidalInsanity** [comment]
Ordinance offset isn't intended for the torp launcher(or twin rail); that's a BDA+ issue, though. BDA-E is just a parts mod.
I cannot confirm the tigershark launch issue; they launch from a max-width torp launcher on my end without issue both submerged and above water; what is your launch setup?
Repulsor hover height is set by the AI default Alt (if using a Pilot/VTOL AI) or 2* max slope angle (if using a surface AI), else it's hardcoded to 10m with no AI on the craft. Changing this would also be a BDA+ issue.

**Comment by Kerbal410** [comment]
perhaps I'm doing something wrong, I have that same setup. would not launching them at max pitch have anything to do with it? where did the torpedo tube model come from? it looks more like a WW2-era turret, though for modern torpedoes. is there an existing ship/class in service with that style rather than the now more typical triangular layout (two on the bottom, one on the top)? I'm not saying there's an issue, just curious.
thanks for letting me know the repulsors work with the surface AI, just differently.
