### ISSUE TITLE
Rim.cfg identity

### ISSUE THREAD

**Issue by Esouder** [BrettRyland/BDArmory-Extended#14]
Is the missile described in [rim.cfg](https://github.com/BrettRyland/BDArmory-Extended/blob/0c1b8083c348b8e3095348c4f4cec6b0ff485745/BDArmoryExtended/Parts/VLSQuad/Assets/RIM.cfg) intended to be like a SeaSparrow/Evolved SeaSparrow (RIM-162), or is it intended to be a similar to a Standard Missile/SM-2 (RIM-66/RIM-67)? The model looks more like an SM, but the texture files are `SeaSparrow.png`. And the localization is both, calling it the RIM-162 Standard Missile. If you can clarify, I'll submit a PR to standardize the localization.

Thanks,
Your local naval missile enjoyer.

**Comment by JovietUnion** [comment]
I think the KH-30 is an analog to the KH-22 Kitchen. It doesn't have the
correct trajectory though. It flies up to 10-14km and flies at mach 4.6. If
there's cruise missile tandem guidance and active seekers integrated to
missiles, they should add active radar

Source:
https://en.m.wikipedia.org/wiki/Kh-22

**Comment by Kerbal410** [comment]
I was just saying that the RIM-162/SM-2 in the mod isn't the only one that combines various elements of different platforms and has mismatched files. just felt a need to provide a little info as well, minus what the real life counterpart was to the Molot, and you are correct with the analog.

**Comment by JovietUnion** [comment]
Yeah. If anything, there should be an addon that provides realistic
performance to the missiles and real names and descriptions. Unless the
altitude is 1500km then hell nah
